# Generated by Django 3.2.9 on 2021-11-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='posters')),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='videos/')),
                ('upload_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
