# Generated by Django 3.2.9 on 2021-11-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='cinema.Movie'),
        ),
    ]
