# Generated by Django 3.2.9 on 2021-11-25 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0002_movie_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
